# Github Actions CI(incheck, 코드 문제 없는지)/CD(deploy)
---
# Workflow 이름
name: Checks
# git push 이벤트 활성화 -> 레포지토리에 push를 했을 때 활성화
on: [push]
# 어떤 역할을 할 거냐
jobs:
  test-lint: # 테스트를 돌린 건데 flake8을 돌릴 거야
    name: Test and Lint
    runs-on: ubuntu-20.04 # 어디서 돌릴 거야?(작업환경)
    steps: # 작업 단계
      - name: Login in to Docker Hub # Docker Hub에서 Image를 불러오는 역할
        uses: docker/login-action@v1 # github actions에서 제공하는 모듈
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Install Docker Compose V2
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
        # +x는 모든 권한을 준다는 의미 == 777

      - name: Check out - Pull repository code # Github에 있는 코드를 작업 환경으로 가져오는 역할
        uses: actions/checkout@v2

      - name: Docker Build
        run: docker compose build app

      - name: Run Test-Code # 이미지와 코드로 테스트
        run: docker-compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"
